name: Create branch associated with issue

on:
  issues:
    types: [opened]

permissions:
  contents: write
  issues: write

jobs:
  create_branch:
    name: Create branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate branch name
        run: |
          # Get issue labels
          labels=$(echo ${LABELS_JSON} | jq -r '.[].name')
          # If both enhancement and bug exist, enhancement takes precedence
          if [[ ${labels} == *"enhancement"* ]]; then
            branch_prefix="feature"
          elif [[ ${labels} == *"bug"* ]]; then
            branch_prefix="fix"
          else
            branch_prefix=""
          fi
          # Get branch name from issue title
          branch_content=$(echo "${TITLE}" | tr ' ' '-' | tr '[:upper:]' '[:lower:]')
          # Set branch name to environment variable
          echo "branch_name=${branch_prefix}/${branch_content}-#${NUMBER}" >> $GITHUB_ENV
        env: 
          LABELS_JSON: ${{ toJson(github.event.issue.labels) }}
          NUMBER: ${{ github.event.issue.number }}
          TITLE: ${{ github.event.issue.title }}

      - name: Create branch associated with issue
          gh issue develop ${NUMBER} --name ${{ env.branch_name }}
        env:
          NUMBER: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
